#!/usr/bin/env node
// Generates the catalog from agent frontmatter — the index is NEVER hand-edited.
//   - index.json                  machine-readable catalog (powers search)
//   - AGENTS.md                   full flat A–Z catalog
//   - categories/<id>/README.md   per-category table
//   - README.md                   category-summary table (between CATALOG markers)
import fs from "node:fs";
import path from "node:path";
import { loadAgents, loadTaxonomy, ROOT } from "./lib/agents.mjs";

const agents = loadAgents();
const taxonomy = loadTaxonomy();
const byId = new Map(taxonomy.categories.map((c) => [c.id, c]));
const modelBadge = (m) => ({ opus: "🔴 opus", sonnet: "🟡 sonnet", haiku: "🟢 haiku" }[m] || `⚪ ${m}`);

// Group agents by category, sorted by name.
const grouped = new Map(taxonomy.categories.map((c) => [c.id, []]));
for (const a of agents) (grouped.get(a.categoryFromPath) ?? []).push(a);
for (const list of grouped.values()) list.sort((x, y) => x.name.localeCompare(y.name));

// ---- index.json -------------------------------------------------------------
const index = {
  total: agents.length,
  categories: taxonomy.categories.map((c) => ({
    id: c.id,
    title: c.title,
    emoji: c.emoji,
    count: (grouped.get(c.id) ?? []).length,
  })),
  agents: agents
    .map((a) => ({
      name: a.name,
      title: a.short,
      category: a.categoryFromPath,
      model: a.model,
      tags: a.tags,
      tools: a.toolList,
      path: a.path,
    }))
    .sort((x, y) => x.name.localeCompare(y.name)),
};
fs.writeFileSync(path.join(ROOT, "index.json"), JSON.stringify(index, null, 2) + "\n");

// ---- per-category README ----------------------------------------------------
for (const c of taxonomy.categories) {
  const list = grouped.get(c.id) ?? [];
  const lines = [
    `# ${c.emoji} ${c.title}`,
    "",
    `> ${c.description}`,
    "",
    `**${list.length} agent${list.length === 1 ? "" : "s"}** · [← Back to all categories](../../README.md)`,
    "",
    "<!-- This file is generated by scripts/build-index.mjs. Do not edit by hand. -->",
    "",
    "| Agent | What it does | Model | Tags |",
    "| --- | --- | --- | --- |",
    ...list.map(
      (a) =>
        `| [\`${a.name}\`](${a.name}.md) | ${a.short || "—"} | ${modelBadge(a.model)} | ${a.tags.slice(0, 4).join(", ")} |`
    ),
    "",
  ];
  fs.writeFileSync(path.join(ROOT, "categories", c.id, "README.md"), lines.join("\n"));
}

// ---- AGENTS.md (flat A–Z) ---------------------------------------------------
const flat = [...agents].sort((x, y) => x.name.localeCompare(y.name));
const agentsMd = [
  "# Full Agent Catalog",
  "",
  `> Auto-generated index of all **${agents.length}** agents, A–Z. See [README.md](README.md) for the category view.`,
  "",
  "<!-- This file is generated by scripts/build-index.mjs. Do not edit by hand. -->",
  "",
  "| Agent | Category | What it does | Model |",
  "| --- | --- | --- | --- |",
  ...flat.map((a) => {
    const c = byId.get(a.categoryFromPath);
    const cat = c ? `${c.emoji} ${c.title}` : a.categoryFromPath;
    return `| [\`${a.name}\`](${a.path}) | ${cat} | ${a.short || "—"} | ${modelBadge(a.model)} |`;
  }),
  "",
];
fs.writeFileSync(path.join(ROOT, "AGENTS.md"), agentsMd.join("\n"));

// ---- README catalog section -------------------------------------------------
const readmePath = path.join(ROOT, "README.md");
const tierCount = (m) => agents.filter((a) => a.model === m).length;
const catalog = [
  "| # | Category | Agents | Focus |",
  "| --- | --- | --- | --- |",
  ...taxonomy.categories.map((c) => {
    const n = (grouped.get(c.id) ?? []).length;
    return `| ${c.id.split("-")[0]} | ${c.emoji} **[${c.title}](categories/${c.id}/README.md)** | ${n} | ${c.description} |`;
  }),
  `| | **Total** | **${agents.length}** | 🔴 ${tierCount("opus")} opus · 🟡 ${tierCount("sonnet")} sonnet · 🟢 ${tierCount("haiku")} haiku |`,
].join("\n");

if (fs.existsSync(readmePath)) {
  const md = fs.readFileSync(readmePath, "utf8");
  const start = "<!-- CATALOG:START -->";
  const end = "<!-- CATALOG:END -->";
  if (md.includes(start) && md.includes(end)) {
    const next = md.replace(
      new RegExp(`${start}[\\s\\S]*?${end}`),
      `${start}\n\n${catalog}\n\n${end}`
    );
    fs.writeFileSync(readmePath, next);
  } else {
    console.warn("⚠ README.md is missing CATALOG markers — skipped README catalog injection.");
  }
}

console.log(`✓ Catalog built: ${agents.length} agents, ${taxonomy.categories.length} categories.`);
console.log(`  index.json · AGENTS.md · ${taxonomy.categories.length} category READMEs · README.md catalog`);
